import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto('http://127.0.0.1:3000/', { waitUntil: 'networkidle' });
await p.waitForTimeout(2000);
await p.screenshot({ path: '/tmp/pg1-retina.png' });
await p.setViewportSize({ width: 390, height: 860 });
await p.waitForTimeout(1000);
await p.screenshot({ path: '/tmp/pg2-mobile.png' });
console.log('ERRORS:', errs.join('\n')||'none');
await b.close();
