import { RestaurantPost } from '../src/types';

// 사전 조사로 확보한 초기 30곳 데이터입니다. 주소·전화번호가 확인되지 않은 곳은
// 정직하게 '확인 필요'로 표시했습니다. 방문자가 직접 글을 쓰면 이 목록에 계속 추가됩니다.
export const RESTAURANT_SEED: RestaurantPost[] = [
  {
    id: 'rest-seed-001',
    courseName: '강릉파크골프장',
    region: '강원 강릉시',
    restaurantName: '정은숙초당순두부',
    menu: '초당두부밥상·두부삼합',
    address: '강원특별자치도 강릉시 난설헌로 200',
    phoneNumber: '0507-1424-3696',
    businessHours: '월 08:00~16:00, 수~일 08:00~18:30 (화요일 휴무)',
    description: 'KBS·SBS 등 방송에 여러 차례 소개된 초당동 순두부마을 대표 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-003',
    courseName: '부주산 국제파크골프장',
    region: '전남·광주 목포시',
    restaurantName: '금메달식당',
    menu: '홍어 코스(회·애·찜·삼합·탕)',
    address: '전남 목포시 후광대로143번길 8',
    phoneNumber: '061-272-2697',
    businessHours: '매일 10:00~22:00',
    description: '홍어의 다양한 부위를 코스로 맛볼 수 있는 목포 대표 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-004',
    courseName: '온고을 파크골프장',
    region: '전북 전주시',
    restaurantName: '한국집',
    menu: '전주비빔밥·육회비빔밥',
    address: '전북 전주시 완산구 어진길 119',
    phoneNumber: '063-284-0086',
    businessHours: '매일 10:30~21:00',
    description: '1979년부터 3대째 이어오는 전주비빔밥 전문점, 백년가게로 인증받았습니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-005',
    courseName: '대전권역 파크골프장',
    region: '충청·대전·세종',
    restaurantName: '성심당 대전역점',
    menu: '튀김소보로·부추빵',
    address: '대전 동구 중앙로 215 (대전역사 2층)',
    phoneNumber: '1588-8069',
    businessHours: '매일 07:00~22:30',
    description: '대전을 대표하는 빵집으로, 기차 타기 전 들르기 좋은 필수 코스입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-016',
    courseName: '강남파크골프장',
    region: '경북 안동시',
    restaurantName: '안동서문찜닭',
    menu: '안동찜닭·쪼림닭',
    address: '경북 안동시 경동로 677 ((구)안동역 맞은편)',
    phoneNumber: '0507-1352-0378',
    businessHours: '매일 10:00~21:00',
    description: '안동역 앞에 위치해 접근성이 좋은 찜닭 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-020',
    courseName: '부주산 국제파크골프장',
    region: '전남·광주 목포시',
    restaurantName: '덕인집',
    menu: '홍어',
    address: '전라남도 목포시 영산로73번길 1-1',
    phoneNumber: '061-242-3767',
    businessHours: '12:00~21:00 (매주 월요일 정기휴무)',
    description: '목포 홍어 맛집 중 평점이 높은 곳으로 다수 소개되었습니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-022',
    courseName: '군산 파크골프장',
    region: '전북 군산시',
    restaurantName: '이성당',
    menu: '단팥빵·야채빵',
    address: '전라북도 군산시 중앙로 177 (중앙로1가)',
    phoneNumber: '063-445-2772',
    businessHours: '매일 08:00~22:00',
    description: '1945년부터 이어온 대한민국에서 가장 오래된 빵집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-024',
    courseName: '부산권역 파크골프장',
    region: '경상 부산시',
    restaurantName: '원조부산밀면',
    menu: '밀면',
    address: '부산 동구 중앙대로23번길 7',
    phoneNumber: '0507-1481-6999',
    businessHours: '매일 10:30~19:00 (라스트오더 18:30)',
    description: '꿩육수를 사용한 담백한 맛으로 유명한 부산 밀면 전문점입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-025',
    courseName: '부산권역 파크골프장',
    region: '경상 부산시 해운대구',
    restaurantName: '가야밀면',
    menu: '밀면',
    address: '부산 해운대구 좌동순환로 27',
    phoneNumber: '051-747-9404',
    businessHours: '09:00~21:00',
    description: '해운대 지역 밀면 맛집으로 다이닝코드에서 높은 평점을 받고 있습니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-026',
    courseName: '제주권역 파크골프장',
    region: '제주시',
    restaurantName: '문치비',
    menu: '흑돼지구이',
    address: '제주 서귀포시 신서로32번길 14 (강정동) 1층',
    phoneNumber: '0507-1409-2560',
    businessHours: '매일 11:00~23:55',
    description: '제주 흑돼지 맛집 중 상위권 평점을 받는 곳입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-027',
    courseName: '제주권역 파크골프장',
    region: '서귀포시',
    restaurantName: '돈사돈 서귀포점',
    menu: '생근고기 흑돼지구이',
    address: '제주 서귀포시 강정마을 인근',
    phoneNumber: '064-738-0779',
    businessHours: '목~화 12:00~21:30 (라스트오더 20:30, 매주 수요일 휴무)',
    description: '100% 제주산 생근고기 흑돼지와 직접 담근 김치찌개가 별미인 곳입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-030',
    courseName: '진해권역 파크골프장',
    region: '경남 창원시 진해구',
    restaurantName: '수백당 자은점',
    menu: '한우곱창전골·순대국·마늘보쌈수육',
    address: '경남 창원시 진해구 냉천북로4번길 18',
    phoneNumber: '055-545-7770',
    businessHours: '11:00~21:30 (브레이크타임 15:00~17:00, 매주 화요일 휴무)',
    description: '마늘소스 수육백반을 최초 개발한 돼지국밥 전문점입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
];