import { RestaurantPost } from '../src/types';

// 사전 조사로 확보한 초기 30곳 데이터입니다. 주소·전화번호가 확인되지 않은 곳은
// 정직하게 '확인 필요'로 표시했습니다. 방문자가 직접 글을 쓰면 이 목록에 계속 추가됩니다.
export const RESTAURANT_SEED: RestaurantPost[] = [
  {
    id: 'rest-seed-001',
    courseName: '강릉파크골프장',
    region: '강원 강릉시',
    restaurantName: '정은숙초당순두부',
    menu: '초당두부밥상·두부삼합',
    address: '강원특별자치도 강릉시 난설헌로 200',
    phoneNumber: '0507-1424-3696',
    businessHours: '월 08:00~16:00, 수~일 08:00~18:30 (화요일 휴무)',
    description: 'KBS·SBS 등 방송에 여러 차례 소개된 초당동 순두부마을 대표 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-002',
    courseName: '경주파크골프 1구장',
    region: '경북 경주시',
    restaurantName: '천마맷돌순두부',
    menu: '맷돌순두부·순두부찌개',
    address: '경북 경주시 첨성로73번길 12',
    phoneNumber: '확인 필요',
    businessHours: '매일 10:00~21:00',
    description: '황리단길 한옥고택에서 30년 역사의 순두부를 맛볼 수 있는 곳입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-003',
    courseName: '부주산 국제파크골프장',
    region: '전남·광주 목포시',
    restaurantName: '금메달식당',
    menu: '홍어 코스(회·애·찜·삼합·탕)',
    address: '전남 목포시 후광대로143번길 8',
    phoneNumber: '061-272-2697',
    businessHours: '매일 10:00~22:00',
    description: '홍어의 다양한 부위를 코스로 맛볼 수 있는 목포 대표 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-004',
    courseName: '온고을 파크골프장',
    region: '전북 전주시',
    restaurantName: '한국집',
    menu: '전주비빔밥·육회비빔밥',
    address: '전북 전주시 완산구 어진길 119',
    phoneNumber: '063-284-0086',
    businessHours: '매일 10:30~21:00',
    description: '1979년부터 3대째 이어오는 전주비빔밥 전문점, 백년가게로 인증받았습니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-005',
    courseName: '대전권역 파크골프장',
    region: '충청·대전·세종',
    restaurantName: '성심당 대전역점',
    menu: '튀김소보로·부추빵',
    address: '대전 동구 중앙로 215 (대전역사 2층)',
    phoneNumber: '1588-8069',
    businessHours: '매일 07:00~22:30',
    description: '대전을 대표하는 빵집으로, 기차 타기 전 들르기 좋은 필수 코스입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-006',
    courseName: '제주권역 파크골프장',
    region: '제주',
    restaurantName: '흑돼지가있는풍경',
    menu: '흑돼지구이·해물구이',
    address: '제주 제주시 진군남4길 7-8',
    phoneNumber: '확인 필요',
    businessHours: '평일 11:00~23:00 (첫째·셋째 화요일 휴무)',
    description: '오겹살과 전복·대하 등 해물을 함께 구워 먹을 수 있는 흑돼지 전문점입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-007',
    courseName: '창원·진해권역 파크골프장',
    region: '경상 창원시',
    restaurantName: '오가네순대곱창',
    menu: '순대전골·순대구이',
    address: '경남 창원시 성산구 가음로117번길 7',
    phoneNumber: '확인 필요',
    businessHours: '10:00~22:00',
    description: '한우곱창전골과 순대구이로 유명한 창원 남양동 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-008',
    courseName: '울주권역 파크골프장',
    region: '울산 울주군',
    restaurantName: '언양불고기식당',
    menu: '언양불고기',
    address: '울산 울주군 언양읍 읍성로 179',
    phoneNumber: '052-264-2904',
    businessHours: '확인 필요',
    description: '울주군 공식 \'울주맛집\'으로 선정된 언양 한우불고기 전문점입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-009',
    courseName: '인천권역 파크골프장',
    region: '인천 남동구',
    restaurantName: '우정이네',
    menu: '소래포구 해산물·회',
    address: '인천 남동구 소래역로 12, 소래포구 종합어시장 2층 237호',
    phoneNumber: '032-719-2237',
    businessHours: '확인 필요',
    description: '소래포구 종합어시장 안에 있는 해산물 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-010',
    courseName: '여의도한강 파크골프장',
    region: '서울 영등포구',
    restaurantName: '장어나루',
    menu: '장어덮밥',
    address: '확인 필요',
    phoneNumber: '확인 필요',
    businessHours: '확인 필요',
    description: '여의도한강공원 인근 맛집 순위에서 꾸준히 상위권으로 소개되는 곳입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-011',
    courseName: '잠실운동장 파크골프장',
    region: '서울 송파구',
    restaurantName: '나폴레옹베이커리',
    menu: '식빵·소세지빵',
    address: '확인 필요',
    phoneNumber: '확인 필요',
    businessHours: '확인 필요',
    description: '잠실종합운동장 사거리 인근에서 오래 자리를 지켜온 베이커리입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-012',
    courseName: '소양강파크골프장',
    region: '강원 춘천시',
    restaurantName: '통나무집닭갈비',
    menu: '숯불 닭갈비·막국수',
    address: '강원 춘천시 소양강댐 인근',
    phoneNumber: '확인 필요',
    businessHours: '확인 필요',
    description: '소양강댐 방향 길목에 있는, 춘천 닭갈비 중 가장 많이 언급되는 곳입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-013',
    courseName: '소양강파크골프장',
    region: '강원 춘천시',
    restaurantName: '장호닭갈비',
    menu: '소금·양념·레몬간장 숯불닭갈비',
    address: '확인 필요',
    phoneNumber: '확인 필요',
    businessHours: '확인 필요',
    description: '연매출 36억에 달하는 춘천의 대표 닭갈비 맛집으로 알려져 있습니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-014',
    courseName: '소양강파크골프장',
    region: '강원 춘천시',
    restaurantName: '남부막국수',
    menu: '막국수',
    address: '확인 필요',
    phoneNumber: '확인 필요',
    businessHours: '확인 필요',
    description: '생활의 달인에 3회 출연한 담백한 막국수 전문점입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-015',
    courseName: '강남파크골프장',
    region: '경북 안동시',
    restaurantName: '중앙찜닭',
    menu: '안동찜닭·조림닭',
    address: '경상북도 안동시 번영1길 51',
    phoneNumber: '054-855-7272',
    businessHours: '확인 필요',
    description: '안동 원조 찜닭거리에서 30년 넘게 이어온 대표 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-016',
    courseName: '강남파크골프장',
    region: '경북 안동시',
    restaurantName: '안동서문찜닭',
    menu: '안동찜닭·쪼림닭',
    address: '경북 안동시 안동역 인근',
    phoneNumber: '확인 필요',
    businessHours: '확인 필요',
    description: '안동역 앞에 위치해 접근성이 좋은 찜닭 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-017',
    courseName: '경주파크골프 2구장',
    region: '경북 경주시',
    restaurantName: '원마중',
    menu: '순두부찌개',
    address: '경북 경주시 황리단길',
    phoneNumber: '확인 필요',
    businessHours: '확인 필요',
    description: '황리단길에서 순두부찌개로 높은 평점을 받는 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-018',
    courseName: '백진공원 파크골프장',
    region: '전남·광주 담양군',
    restaurantName: '신식당',
    menu: '떡갈비·대통밥',
    address: '전라남도 담양군 담양읍 담주2길 18-13',
    phoneNumber: '061-382-9901',
    businessHours: '확인 필요',
    description: '1932년 창업해 4대째 이어오는 담양 떡갈비 전문점입니다. 주차 가능(30대), 168석 규모입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-019',
    courseName: '백진공원 파크골프장',
    region: '전남·광주 담양군',
    restaurantName: '담양앞집',
    menu: '댓잎비빔국수·매운떡갈비국수',
    address: '전남 담양군',
    phoneNumber: '확인 필요',
    businessHours: '확인 필요',
    description: '담양 특산물인 댓잎을 넣은 자가제면 국수로 유명한 곳입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-020',
    courseName: '부주산 국제파크골프장',
    region: '전남·광주 목포시',
    restaurantName: '덕인집',
    menu: '홍어',
    address: '전남 목포시',
    phoneNumber: '확인 필요',
    businessHours: '확인 필요',
    description: '목포 홍어 맛집 중 평점이 높은 곳으로 다수 소개되었습니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-021',
    courseName: '온고을 파크골프장',
    region: '전북 전주시',
    restaurantName: '하숙영가마솥비빔밥',
    menu: '가마솥비빔밥',
    address: '전북 전주시 한옥마을',
    phoneNumber: '확인 필요',
    businessHours: '확인 필요',
    description: '전주한옥마을 비빔밥 맛집 중 상위권으로 꼽히는 곳입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-022',
    courseName: '군산 파크골프장',
    region: '전북 군산시',
    restaurantName: '이성당',
    menu: '단팥빵·야채빵',
    address: '전북 군산시 중앙로1가 12-2',
    phoneNumber: '확인 필요',
    businessHours: '매일 08:00~22:00',
    description: '1945년부터 이어온 대한민국에서 가장 오래된 빵집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-023',
    courseName: '대구권역 파크골프장',
    region: '경상 대구시',
    restaurantName: '삼송빵집',
    menu: '통옥수수빵(\'마약빵\')',
    address: '대구 중구 중앙대로 397',
    phoneNumber: '확인 필요',
    businessHours: '매일 08:00~22:00',
    description: '1957년부터 이어온 대구 대표 빵집으로 \'마약빵\'이 유명합니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-024',
    courseName: '부산권역 파크골프장',
    region: '경상 부산시',
    restaurantName: '원조부산밀면',
    menu: '밀면',
    address: '부산 동구 중앙대로23번길 7',
    phoneNumber: '0507-1481-6999',
    businessHours: '매일 10:30~19:00 (라스트오더 18:30)',
    description: '꿩육수를 사용한 담백한 맛으로 유명한 부산 밀면 전문점입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-025',
    courseName: '부산권역 파크골프장',
    region: '경상 부산시 해운대구',
    restaurantName: '가야밀면',
    menu: '밀면',
    address: '부산 해운대구 좌동순환로 27',
    phoneNumber: '051-747-9404',
    businessHours: '09:00~21:00',
    description: '해운대 지역 밀면 맛집으로 다이닝코드에서 높은 평점을 받고 있습니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-026',
    courseName: '제주권역 파크골프장',
    region: '제주시',
    restaurantName: '문치비',
    menu: '흑돼지구이',
    address: '제주 서귀포시 신서로32번길 14 (강정동) 1층',
    phoneNumber: '0507-1409-2560',
    businessHours: '매일 11:00~23:55',
    description: '제주 흑돼지 맛집 중 상위권 평점을 받는 곳입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-027',
    courseName: '제주권역 파크골프장',
    region: '서귀포시',
    restaurantName: '돈사돈 서귀포점',
    menu: '생근고기 흑돼지구이',
    address: '제주 서귀포시 강정마을 인근',
    phoneNumber: '064-738-0779',
    businessHours: '목~화 12:00~21:30 (라스트오더 20:30, 매주 수요일 휴무)',
    description: '100% 제주산 생근고기 흑돼지와 직접 담근 김치찌개가 별미인 곳입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-028',
    courseName: '청주권역 파크골프장',
    region: '충북 청주시',
    restaurantName: '원조육거리순대',
    menu: '순대국밥',
    address: '충북 청주시 육거리시장',
    phoneNumber: '확인 필요',
    businessHours: '확인 필요',
    description: '청주 육거리시장의 대표 순대국밥 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-029',
    courseName: '충주권역 파크골프장',
    region: '충북 충주시',
    restaurantName: '일번지순대국',
    menu: '순대국',
    address: '충북 충주시',
    phoneNumber: '확인 필요',
    businessHours: '확인 필요',
    description: '충주 지역 순대국 맛집 중 상위권으로 꼽힙니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-030',
    courseName: '진해권역 파크골프장',
    region: '경남 창원시 진해구',
    restaurantName: '수백당 자은점',
    menu: '한우곱창전골·순대국·마늘보쌈수육',
    address: '경남 창원시 진해구 냉천북로4번길 18',
    phoneNumber: '055-545-7770',
    businessHours: '11:00~21:30 (브레이크타임 15:00~17:00, 매주 화요일 휴무)',
    description: '마늘소스 수육백반을 최초 개발한 돼지국밥 전문점입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
];