import { RestaurantPost } from '../src/types';

// 사전 조사로 확보한 초기 30곳 데이터입니다. 주소·전화번호가 확인되지 않은 곳은
// 주소·전화번호·영업시간이 전부 확인된 곳만 남겼습니다. 방문자가 직접 글을 쓰면 이 목록에 계속 추가됩니다.
export const RESTAURANT_SEED: RestaurantPost[] = [
  {
    id: 'rest-seed-001',
    courseName: '강릉파크골프장',
    region: '강원 강릉시',
    restaurantName: '정은숙초당순두부',
    menu: '초당두부밥상·두부삼합',
    address: '강원특별자치도 강릉시 난설헌로 200 (초당동)',
    phoneNumber: '033-652-3696',
    businessHours: '월 08:00~16:00 / 수~일 08:00~18:30',
    description: 'KBS·SBS 등 방송에 여러 차례 소개된 초당동 순두부마을 대표 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-003',
    courseName: '부주산 국제파크골프장',
    region: '전남·광주 목포시',
    restaurantName: '금메달식당',
    menu: '홍어 코스(회·애·찜·삼합·탕)',
    address: '전라남도 목포시 입암로42번길 15-1',
    phoneNumber: '061-272-2697',
    businessHours: '매일 10:00~22:00',
    description: '홍어의 다양한 부위를 코스로 맛볼 수 있는 목포 대표 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-004',
    courseName: '온고을 파크골프장',
    region: '전북 전주시',
    restaurantName: '한국집',
    menu: '전주비빔밥·육회비빔밥',
    address: '전북특별자치도 전주시 완산구 어진길 119',
    phoneNumber: '063-284-2224',
    businessHours: '09:30~21:00 / 브레이크 16:00~17:00',
    description: '1979년부터 3대째 이어오는 전주비빔밥 전문점, 백년가게로 인증받았습니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-005',
    courseName: '대전권역 파크골프장',
    region: '충청·대전·세종',
    restaurantName: '성심당 대전역점',
    menu: '튀김소보로·부추빵',
    address: '대전 동구 중앙로 215 (대전역사 2층)',
    phoneNumber: '1588-8069',
    businessHours: '매일 07:00~22:30',
    description: '대전을 대표하는 빵집으로, 기차 타기 전 들르기 좋은 필수 코스입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-016',
    courseName: '강남파크골프장',
    region: '경북 안동시',
    restaurantName: '안동서문찜닭',
    menu: '안동찜닭·쪼림닭',
    address: '경북 안동시 경동로 677 ((구)안동역 맞은편)',
    phoneNumber: '0507-1352-0378',
    businessHours: '매일 10:00~21:00',
    description: '안동역 앞에 위치해 접근성이 좋은 찜닭 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-020',
    courseName: '부주산 국제파크골프장',
    region: '전남·광주 목포시',
    restaurantName: '덕인집',
    menu: '홍어',
    address: '전라남도 목포시 영산로73번길 1-1',
    phoneNumber: '061-242-3767',
    businessHours: '화~일 12:00~21:00',
    description: '목포 홍어 맛집 중 평점이 높은 곳으로 다수 소개되었습니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-022',
    courseName: '군산 파크골프장',
    region: '전북 군산시',
    restaurantName: '이성당',
    menu: '단팥빵·야채빵',
    address: '전라북도 군산시 중앙로 177 (중앙로1가)',
    phoneNumber: '063-445-2772',
    businessHours: '매일 08:00~22:00',
    description: '1945년부터 이어온 대한민국에서 가장 오래된 빵집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-024',
    courseName: '부산권역 파크골프장',
    region: '경상 부산시',
    restaurantName: '원조부산밀면',
    menu: '밀면',
    address: '부산 동구 중앙대로23번길 7',
    phoneNumber: '0507-1481-6999',
    businessHours: '매일 10:30~19:00 (라스트오더 18:30)',
    description: '꿩육수를 사용한 담백한 맛으로 유명한 부산 밀면 전문점입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-025',
    courseName: '부산권역 파크골프장',
    region: '경상 부산시 해운대구',
    restaurantName: '가야밀면',
    menu: '밀면',
    address: '부산 해운대구 좌동순환로 27',
    phoneNumber: '051-747-9404',
    businessHours: '09:00~21:00',
    description: '해운대 지역 밀면 맛집으로 다이닝코드에서 높은 평점을 받고 있습니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-026',
    courseName: '제주권역 파크골프장',
    region: '제주시',
    restaurantName: '문치비',
    menu: '흑돼지구이',
    address: '제주 서귀포시 신서로32번길 14 (강정동) 1층',
    phoneNumber: '0507-1409-2560',
    businessHours: '매일 11:00~23:55',
    description: '제주 흑돼지 맛집 중 상위권 평점을 받는 곳입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-027',
    courseName: '제주권역 파크골프장',
    region: '서귀포시',
    restaurantName: '돈사돈 서귀포점',
    menu: '생근고기 흑돼지구이',
    address: '제주 서귀포시 강정마을 인근',
    phoneNumber: '064-738-0779',
    businessHours: '목~화 12:00~21:30 (라스트오더 20:30, 매주 수요일 휴무)',
    description: '100% 제주산 생근고기 흑돼지와 직접 담근 김치찌개가 별미인 곳입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },
  {
    id: 'rest-seed-030',
    courseName: '진해권역 파크골프장',
    region: '경남 창원시 진해구',
    restaurantName: '수백당 자은점',
    menu: '한우곱창전골·순대국·마늘보쌈수육',
    address: '경남 창원시 진해구 냉천북로4번길 18',
    phoneNumber: '055-545-7770',
    businessHours: '11:00~21:30 (브레이크타임 15:00~17:00, 매주 화요일 휴무)',
    description: '마늘소스 수육백반을 최초 개발한 돼지국밥 전문점입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-04'
  },

  {
    id: 'rest-seed-100',
    courseName: '경주파크골프장(1구장)',
    region: '경북 경주',
    restaurantName: '천마맷돌순두부',
    menu: '메뉴 정보 확인 중',
    address: '경상북도 경주시 첨성로73번길 12',
    phoneNumber: '054-705-0022',
    businessHours: '매일 10:00~21:00',
    description: '경주파크골프장(1구장) 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-101',
    courseName: '잠실파크골프장',
    region: '서울 송파',
    restaurantName: '나폴레옹과자점 잠실점',
    menu: '메뉴 정보 확인 중',
    address: '서울특별시 송파구 백제고분로 67',
    phoneNumber: '02-415-1144',
    businessHours: '매일 08:00~22:30',
    description: '잠실파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-102',
    courseName: '춘천 소양강파크골프장',
    region: '강원 춘천',
    restaurantName: '통나무집닭갈비 본점',
    menu: '메뉴 정보 확인 중',
    address: '강원특별자치도 춘천시 신북읍 신샘밭로 763',
    phoneNumber: '033-241-5999',
    businessHours: '매일 10:30~21:30 (라스트오더 20:30)',
    description: '춘천 소양강파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-103',
    courseName: '춘천 소양강파크골프장',
    region: '강원 춘천',
    restaurantName: '장호닭갈비명가',
    menu: '메뉴 정보 확인 중',
    address: '강원특별자치도 춘천시 신북읍 신샘밭로 676',
    phoneNumber: '033-242-5877',
    businessHours: '월~토 10:00~21:00 / 일요일 운영시간 방문 전 확인',
    description: '춘천 소양강파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-104',
    courseName: '춘천 소양강파크골프장',
    region: '강원 춘천',
    restaurantName: '남부막국수 본관',
    menu: '메뉴 정보 확인 중',
    address: '강원특별자치도 춘천시 춘천로81번길 16',
    phoneNumber: '033-254-7859',
    businessHours: '매일 10:00~20:30',
    description: '춘천 소양강파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-105',
    courseName: '가평파크골프장',
    region: '경기 가평',
    restaurantName: '고우다 가평본점',
    menu: '메뉴 정보 확인 중',
    address: '경기도 가평군 청평면 호명리 362-14',
    phoneNumber: '031-584-4423',
    businessHours: '매일 11:00~22:00',
    description: '가평파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-106',
    courseName: '가평파크골프장',
    region: '경기 가평',
    restaurantName: '이경숙할머니음식점',
    menu: '메뉴 정보 확인 중',
    address: '경기도 가평군 청평면 삼회리 189-37',
    phoneNumber: '031-584-0064',
    businessHours: '매일 10:00~21:00',
    description: '가평파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-107',
    courseName: '강남탄천파크골프장',
    region: '서울 강남',
    restaurantName: '바이탈바이브',
    menu: '메뉴 정보 확인 중',
    address: '서울특별시 강남구 세곡동 171-11',
    phoneNumber: '02-6953-3414',
    businessHours: '매일 10:00~21:00',
    description: '강남탄천파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-108',
    courseName: '고양 한별파크골프장',
    region: '경기 고양',
    restaurantName: '금수강산',
    menu: '메뉴 정보 확인 중',
    address: '경기도 고양시 덕양구 고양동 혜음로107번길 29',
    phoneNumber: '031-969-3461',
    businessHours: '매일 10:30~22:00',
    description: '고양 한별파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-109',
    courseName: '광명 소하파크골프장',
    region: '경기 광명',
    restaurantName: '우리식당',
    menu: '메뉴 정보 확인 중',
    address: '경기도 광명시 충현로 1',
    phoneNumber: '02-897-7012',
    businessHours: '매일 06:00~19:30',
    description: '광명 소하파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-110',
    courseName: '광명 소하파크골프장',
    region: '경기 광명',
    restaurantName: '돼지집',
    menu: '메뉴 정보 확인 중',
    address: '경기도 광명시 기아로 56',
    phoneNumber: '02-805-9407',
    businessHours: '매일 08:30~23:00',
    description: '광명 소하파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-111',
    courseName: '구리 인창파크골프장',
    region: '경기 구리',
    restaurantName: '공인인증소',
    menu: '메뉴 정보 확인 중',
    address: '경기도 구리시 건원대로 71 (인창동)',
    phoneNumber: '0504-4649-4983',
    businessHours: '매일 12:00~24:00',
    description: '구리 인창파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-112',
    courseName: '구리 인창파크골프장',
    region: '경기 구리',
    restaurantName: '선도유통',
    menu: '메뉴 정보 확인 중',
    address: '경기도 구리시 동구릉로136번길 90 (인창동)',
    phoneNumber: '0504-0559-2504',
    businessHours: '매일 09:00~21:00',
    description: '구리 인창파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-113',
    courseName: '구리 인창파크골프장',
    region: '경기 구리',
    restaurantName: '호레타',
    menu: '메뉴 정보 확인 중',
    address: '경기도 구리시 경춘로227번길 6-15 1층',
    phoneNumber: '0507-1415-7029',
    businessHours: '11:30~21:00 / 브레이크 15:00~16:30',
    description: '구리 인창파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-114',
    courseName: '구리 인창파크골프장',
    region: '경기 구리',
    restaurantName: '정진식당',
    menu: '메뉴 정보 확인 중',
    address: '경기도 구리시 교문동 199-1',
    phoneNumber: '031-552-5253',
    businessHours: '매일 11:00~22:00',
    description: '구리 인창파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-115',
    courseName: '구리 인창파크골프장',
    region: '경기 구리',
    restaurantName: '잉꼬칼국수',
    menu: '메뉴 정보 확인 중',
    address: '경기도 구리시 교문동 226-30',
    phoneNumber: '031-564-3354',
    businessHours: '월~토 10:30~20:00',
    description: '구리 인창파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-116',
    courseName: '기형도문화공원 파크골프장',
    region: '경기 광명',
    restaurantName: '돼지집',
    menu: '메뉴 정보 확인 중',
    address: '경기도 광명시 기아로 56',
    phoneNumber: '02-805-9407',
    businessHours: '매일 08:30~23:00',
    description: '기형도문화공원 파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-117',
    courseName: '관악파크골프장',
    region: '서울 관악',
    restaurantName: '고기싸롱 난곡점',
    menu: '메뉴 정보 확인 중',
    address: '서울특별시 관악구 난곡로 186 101호',
    phoneNumber: '02-830-7759',
    businessHours: '매일 11:30~23:00',
    description: '관악파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-118',
    courseName: '관악파크골프장',
    region: '서울 관악',
    restaurantName: '명태어장 난곡점',
    menu: '메뉴 정보 확인 중',
    address: '서울특별시 관악구 난곡로 180',
    phoneNumber: '02-868-6062',
    businessHours: '매일 11:00~21:30 (라스트오더 21:00)',
    description: '관악파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-119',
    courseName: '관악파크골프장',
    region: '서울 관악',
    restaurantName: '엄마손칼국수&전',
    menu: '메뉴 정보 확인 중',
    address: '서울특별시 관악구 난곡로35길 5',
    phoneNumber: '02-6449-7279',
    businessHours: '11:30~22:00 / 브레이크 15:00~17:00 (주 1회 휴무, 요일은 방문 전 확인)',
    description: '관악파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-120',
    courseName: '관악파크골프장',
    region: '서울 관악',
    restaurantName: '난곡산장',
    menu: '메뉴 정보 확인 중',
    address: '서울특별시 관악구 난곡로 170-6',
    phoneNumber: '02-858-5255',
    businessHours: '11:00~22:00 (주 1회 휴무 표기, 방문 전 확인)',
    description: '관악파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-121',
    courseName: '관악파크골프장',
    region: '서울 관악',
    restaurantName: '고봉밥이야기',
    menu: '메뉴 정보 확인 중',
    address: '서울특별시 관악구 법원단지3길 3',
    phoneNumber: '02-830-1436',
    businessHours: '매일 10:30~23:00 / 브레이크 15:00~17:00 / 격주 일요일 휴무',
    description: '관악파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-122',
    courseName: '계양경기장 파크골프장',
    region: '인천 계양',
    restaurantName: '백암토종왕순대',
    menu: '메뉴 정보 확인 중',
    address: '인천광역시 계양구 효서로 356',
    phoneNumber: '032-542-3844',
    businessHours: '화~일 09:00~22:00 / 월요일 휴무 / 라스트오더 21:30',
    description: '계양경기장 파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-123',
    courseName: '군포 초막골파크골프장',
    region: '경기 군포',
    restaurantName: '산본우동',
    menu: '메뉴 정보 확인 중',
    address: '경기도 군포시 산본동 수리산로 42',
    phoneNumber: '031-391-5155',
    businessHours: '월~금·일 11:00~22:00 / 토 11:00~22:30',
    description: '군포 초막골파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-124',
    courseName: '기흥호수공원 파크골프장',
    region: '경기 용인',
    restaurantName: '더뷰17',
    menu: '메뉴 정보 확인 중',
    address: '경기도 용인시 기흥구 한일로9번길 33 2,3층',
    phoneNumber: '031-285-0246',
    businessHours: '매일 11:00~21:20 / 브레이크 15:40~17:00 / 라스트오더 20:40',
    description: '기흥호수공원 파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-125',
    courseName: '기흥호수공원 파크골프장',
    region: '경기 용인',
    restaurantName: '큰손식당',
    menu: '메뉴 정보 확인 중',
    address: '경기도 용인시 기흥구 공세로 243 (공세동)',
    phoneNumber: '031-287-3383',
    businessHours: '화~토 11:00~22:00 / 브레이크 15:30~17:00 / 라스트오더 21:00 / 일·월 휴무',
    description: '기흥호수공원 파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-126',
    courseName: '나리공원파크골프장',
    region: '경기 양주',
    restaurantName: '조리고 양주점',
    menu: '메뉴 정보 확인 중',
    address: '경기도 양주시 광사로 134 2층',
    phoneNumber: '031-821-5678',
    businessHours: '매일 11:00~21:00 / 브레이크 15:30~16:30 / 라스트오더 20:20',
    description: '나리공원파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
  {
    id: 'rest-seed-127',
    courseName: '나리공원파크골프장',
    region: '경기 양주',
    restaurantName: '양주불백',
    menu: '메뉴 정보 확인 중',
    address: '경기도 양주시 외미로 89',
    phoneNumber: '031-821-1616',
    businessHours: '매일 11:00~22:00',
    description: '나리공원파크골프장 인근 검증된 맛집입니다.',
    authorName: '운영자(사전조사)',
    createdAt: '2026-09-06'
  },
];